### ISSUE TITLE
The browser cache problem

### ISSUE THREAD

**Issue by jim972329667** [marcrobledo/minidex#5]
The browser cache storage cannot be automatically updated. Although the site has been updated, the local cache still needs to be manually updated.
![Cache Storage](https://user-images.githubusercontent.com/59948910/101707949-42e2e100-3ac7-11eb-8ee2-0ba28c2a1ade.png)

**Comment by marcrobledo** [comment]
Yes, I was waiting for the next big update to be done before forcing the cache refresh.

Since 97df90e7d8879b2ed52b063b98f5b6986bd43e6b it should automatically refresh your cache during your first visit since the update.

**Comment by marcrobledo** [comment]
Also, the search bar should work now with japanese and chinese names, let me know if it works!

**Comment by jim972329667** [comment]
The location and Pokemon Search will now work properly.
